version: "3.7"

services:
    alfresco:
        image: alfresco/alfresco-content-repository-community:latest
        environment:
            CATALINA_OPTS : "
                -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
                "                
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dalfresco.restApi.basicAuthScheme=true
                -Dimap.server.enabled=true
                -Dftp.enabled=true
                -Dftp.dataPortFrom=30000
                -Dftp.dataPortTo=30099
                -Dshare.port=8084
                -Dshare.host=share
                -Daos.baseUrlOverwrite=http://alfresco:8082/alfresco/aos
                -Dmessaging.broker.url=\"failover:(tcp://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dlocal.transform.service.enabled=true
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/
                -Dlegacy.transform.service.enabled=true
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/
                -Dcsrf.filter.enabled=false
                -Xms1500m -Xmx1500m
                "
        ports:
            - 8082:8080 #Browser port
            - 8000:8000
            - 143:1143
            - "21:1221"
            #- "30000-30099:30000-30099"
        volumes:
            - alfresco:/usr/local/tomcat/alf_data
        deploy:
            resources:
                limits:
                    memory: 2G
                    cpus: '3.0'
        links:
            - postgres
            - share
            - solr6
            - activemq
            - alfresco-pdf-renderer
            - imagemagick
            - libreoffice
            - tika
            - transform-misc

    share:
        image: alfresco/alfresco-share:6.1.0-RC3
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080
        ports:
            - 8084:8080
        deploy:
            resources:
                limits:
                    memory: 8G
                    cpus: '4.0'

    postgres:
        image: postgres:latest 
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - backups:/backups
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

    solr6:
        image: alfresco/alfresco-search-services:1.3.0.6
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        ports:
            - 8083:8983 #Browser port
        volumes:
            - solr-data:/opt/alfresco-search-services/data
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'            

    activemq:
        image: webcenter/activemq:latest
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: '2.0'

###extras###    

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:latest
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8090:8090
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

    imagemagick:
        image: alfresco/alfresco-imagemagick:latest
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8091:8090
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

    libreoffice:
        image: alfresco/alfresco-libreoffice:latest
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8092:8090
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

    tika:
        image: alfresco/alfresco-tika:latest
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8093:8090
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

    transform-misc:
        image: alfresco/alfresco-transform-misc:latest
        environment:
            JAVA_OPTS: " -Xms256m -Xmx256m"
        ports:
            - 8094:8090
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'
    pgbackups:
        image: prodrigestivill/postgres-backup-local
        restart: always
        volumes:
            - backups:/backups
        links:
            - postgres
        depends_on:
            - postgres
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_PASSWORD=alfresco
#           - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
            - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
            - SCHEDULE=@daily
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
            - HEALTHCHECK_PORT=80
        deploy:
            resources:
                limits:
                    memory: 1G
                    cpus: '2.0'

####fim dos componentes extras###            
                
volumes:
    postgres-data:
    alfresco:
    backups:
    solr-data:
